version: '4'
services:
  mysql:
    image: mysql:latest
    container_name: garagem_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: garagem
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./db/Create_carros_garagem.sql:/docker-entrypoint-initdb.d/Create_carros_garagem.sql"
      - ./my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf
